import * as functions from "firebase-functions";
import * as admin from "firebase-admin";
import {FieldValue} from "firebase-admin/firestore";

/**
 * Cloud function to fetch existing ideas for a lead
 * Works with ideas generated by any idea generator (GenAI, custom, etc.)
 */
export const getLeadIdeas = functions.https.onCall(
  async (data, context) => {
    // Verify authentication
    if (!context.auth) {
      throw new functions.https.HttpsError(
        "unauthenticated",
        "User must be authenticated to fetch ideas"
      );
    }

    const {leadId} = data;

    if (!leadId || typeof leadId !== "string") {
      throw new functions.https.HttpsError(
        "invalid-argument",
        "Lead ID is required and must be a string"
      );
    }

    try {
      const db = admin.firestore();
      const ideasSnapshot = await db
        .collection("leads")
        .doc(leadId)
        .collection("ideas")
        .orderBy("createdAt", "desc")
        .get();

      const ideas = ideasSnapshot.docs.map((doc) => ({
        id: doc.id,
        ...doc.data(),
      }));

      return {
        ideas,
        total: ideas.length,
      };
    } catch (error: any) {
      console.error("Error fetching ideas:", error);
      throw new functions.https.HttpsError(
        "internal",
        `Failed to fetch ideas: ${error.message || "Unknown error"}`
      );
    }
  }
);

/**
 * Cloud function to update idea status (approve, attach, etc.)
 * Works with ideas generated by any idea generator (GenAI, custom, etc.)
 */
export const updateIdeaStatus = functions.https.onCall(
  async (data, context) => {
    // Verify authentication
    if (!context.auth) {
      throw new functions.https.HttpsError(
        "unauthenticated",
        "User must be authenticated to update ideas"
      );
    }

    const {leadId, ideaId, status} = data;

    if (!leadId || typeof leadId !== "string") {
      throw new functions.https.HttpsError(
        "invalid-argument",
        "Lead ID is required and must be a string"
      );
    }

    if (!ideaId || typeof ideaId !== "string") {
      throw new functions.https.HttpsError(
        "invalid-argument",
        "Idea ID is required and must be a string"
      );
    }

    if (!["pending", "approved", "attached"].includes(status)) {
      throw new functions.https.HttpsError(
        "invalid-argument",
        "Status must be one of: pending, approved, attached"
      );
    }

    try {
      const db = admin.firestore();
      const ideaRef = db
        .collection("leads")
        .doc(leadId)
        .collection("ideas")
        .doc(ideaId);

      const updateData: any = {
        status,
        updatedAt: FieldValue.serverTimestamp(),
      };

      if (status === "attached") {
        updateData.attachedAt = FieldValue.serverTimestamp();
      }

      await ideaRef.update(updateData);

      console.log(`Updated idea ${ideaId} status to ${status} for lead ${leadId}`);

      return {
        success: true,
        ideaId,
        status,
      };
    } catch (error: any) {
      console.error("Error updating idea status:", error);
      throw new functions.https.HttpsError(
        "internal",
        `Failed to update idea status: ${error.message || "Unknown error"}`
      );
    }
  }
);
